services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_management
    ports:
      - "5555:5432"
    volumes:
      - ./server/db_data:/var/lib/postgresql/